name: Forecasting CD

on:
  workflow_run:
    workflows: [ "Forecasting CI (Self-Hosted)" ]   # must match the job name in ci.yml
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest          # self-hosted or ubuntu-latest also fine
    permissions:
      contents: write                # required when you rely on GITHUB_TOKEN

    steps:
    - name: Download model artifact
      uses: actions/download-artifact@v4.2.1   # ← explicit tag
      with:
        name: transformer-model
        path: ./artifact

    - name: Push model to AdEva-ausgrid repository
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}   # built-in token works for same-org repos
      shell: pwsh
      run: |
        git clone https://$env:TOKEN@github.com/nutsfinder/AdEva-ausgrid.git app
        Copy-Item artifact\transformer.pt app\models\transformer.pt -Force
        cd app
        git config user.email "ci@github.com"
        git config user.name  "ci-bot"
        git add models/transformer.pt
        git commit -m "CI: update model to $env:GITHUB_SHA"
        git push origin main
